<?php

namespace App\Livewire;

use Livewire\Component;
use App\Models\Proforma;
use App\Models\ProformaInvoice;
use Illuminate\Support\Facades\DB;

class AdminSendToOwnerModal extends Component
{
    public $showModal = false;
    public $proformaId;
    public $proforma;
    public $proformaType = 'regular'; // 'regular' or 'etera_chereta'
    public $requestedCount;
    public $unitPrice = 0;
    public $hourlyPrice = 0;
    public $hours = 0;
    public $vatRate = 15; // 15% VAT
    public $subtotal = 0;
    public $vatAmount = 0;
    public $totalAmount = 0;

    protected $rules = [
        'proformaType' => 'required|in:regular,etera_chereta',
        'requestedCount' => 'required|integer|min:1',
        'unitPrice' => 'required_if:proformaType,regular|numeric|min:0',
        'hourlyPrice' => 'required_if:proformaType,etera_chereta|numeric|min:0',
        'hours' => 'required_if:proformaType,etera_chereta|integer|min:1',
    ];

    public function mount()
    {
        $this->resetForm();
    }

    public function openModal($proformaId)
    {
        $this->proformaId = $proformaId;
        $this->proforma = Proforma::find($proformaId);
        
        if ($this->proforma) {
            $this->proformaType = $this->proforma->isEteraCheretaMode() ? 'etera_chereta' : 'regular';
            $this->requestedCount = $this->proforma->required_number_of_shops ?? 1;
            // The timer_duration is in minutes, so we convert it to hours.
            $this->hours = $this->proforma->timer_duration ? ($this->proforma->timer_duration / 60) : 24;
        }
        
        $this->showModal = true;
        $this->calculateTotals();
    }

    public function closeModal()
    {
        $this->showModal = false;
        $this->resetForm();
    }

    public function updated($propertyName)
    {
        $this->validateOnly($propertyName);
        $this->calculateTotals();
    }

    public function calculateTotals()
    {
        if ($this->proformaType === 'etera_chereta') {
            $this->subtotal = is_numeric($this->hourlyPrice) && is_numeric($this->hours) ? ($this->hourlyPrice * $this->hours) : 0;
        } else {
            $this->subtotal = is_numeric($this->unitPrice) && is_numeric($this->requestedCount) ? ($this->unitPrice * $this->requestedCount) : 0;
        }
        
        $this->vatAmount = ($this->subtotal * $this->vatRate) / 100;
        $this->totalAmount = $this->subtotal + $this->vatAmount;
    }

    public function sendToOwner()
    {
        $this->validate();
        $this->calculateTotals();

        DB::beginTransaction();
        try {
            // Create invoice record (SKU auto-generated by model boot)
            $invoice = ProformaInvoice::create([
                'proforma_id' => $this->proformaId,
                'type' => $this->proformaType,
                'requested_count' => $this->requestedCount,
                'unit_price' => $this->unitPrice,
                'hourly_price' => $this->hourlyPrice,
                'hours' => $this->hours,
                'vat_rate' => $this->vatRate,
                'vat_amount' => $this->vatAmount,
                'total_amount' => $this->totalAmount,
                'created_by' => auth()->id(),
            ]);

            // Update proforma status
            $this->proforma->update([
                'status' => 'sent_to_owner',
                'verified' => true,
            ]);

            DB::commit();

            // Notify the poster via database notification (bell icon)
            try {
                if ($this->proforma->poster) {
                    $this->proforma->poster->notify(
                        new \App\Notifications\ProformaSentToOwnerNotification($this->proforma)
                    );
                }
            } catch (\Throwable $e) {
                \Illuminate\Support\Facades\Log::warning('Failed to send sent-to-owner notification', ['error' => $e->getMessage()]);
            }

            // Send Telegram notification with invoice link to poster
            try {
                if ($this->proforma->poster && !empty($this->proforma->poster->telegram_chat_id)) {
                    $invoiceUrl = url("/transaction/{$invoice->sku}");
                    (new \App\Services\TelegramService())->sendSentToOwnerNotification(
                        $this->proforma->poster->telegram_chat_id,
                        $this->proforma,
                        $invoiceUrl
                    );
                }
            } catch (\Throwable $e) {
                \Illuminate\Support\Facades\Log::warning('Telegram send-to-owner notification failed', [
                    'proforma_id' => $this->proforma->id,
                    'error' => $e->getMessage(),
                ]);
            }

            // Broadcast via Reverb
            try {
                if ($this->proforma->poster) {
                    event(new \App\Events\ProformaStatusChanged($this->proforma, 'sent_to_owner', $this->proforma->poster_id));
                    event(new \App\Events\NotificationSent($this->proforma->poster->id, [
                        'message' => 'Proforma #' . $this->proforma->file_number . ' has been completed and returned to you',
                        'type' => 'proforma_sent_to_owner',
                        'file_number' => $this->proforma->file_number,
                        'proforma_id' => $this->proforma->id,
                    ], $this->proforma->poster->unreadNotifications()->count()));
                }
            } catch (\Throwable $e) {
                \Illuminate\Support\Facades\Log::warning('Broadcast sent-to-owner event failed', ['error' => $e->getMessage()]);
            }
            
            $this->closeModal();
            $this->dispatch('proforma-sent', [
                'message' => 'Proforma sent to owner successfully!',
                'type' => 'success'
            ]);
            
        } catch (\Exception $e) {
            DB::rollBack();
            $this->dispatch('proforma-sent', [
                'message' => 'Error sending proforma: ' . $e->getMessage(),
                'type' => 'error'
            ]);
        }
    }

    public function resetForm()
    {
        $this->proformaId = null;
        $this->proforma = null;
        $this->proformaType = 'regular';
        $this->requestedCount = 1;
        $this->unitPrice = 0;
        $this->hourlyPrice = 0;
        $this->hours = 0;
        $this->subtotal = 0;
        $this->vatAmount = 0;
        $this->totalAmount = 0;
    }

    public function render()
    {
        return view('livewire.admin-send-to-owner-modal');
    }
}